import { expect, test } from '@playwright/test'
import { dragMillimetres, drawStarterRectangle, drawStudioShape, screenPoint } from './part-studio-helpers'

for (const viewport of [{ width: 390, height: 844 }, { width: 768, height: 1024 }, { width: 1440, height: 900 }]) {
  test(`ordinary cuts and explicit slot positions at ${viewport.width}px`, async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
    await page.setViewportSize(viewport)
    await page.goto('/register')
    await page.getByRole('button', { name: '进入游客模式', exact: true }).click()
    await page.goto('/part-studio')
    const canvas = await drawStarterRectangle(page)
    const tools = page.getByRole('group', { name: '绘图工具', exact: true })
    const input = (name: string) => page.getByRole('spinbutton', { name: `${name}（毫米）`, exact: true })
    const save = page.getByRole('button', { name: '保存', exact: true })
    await drawStudioShape(page, '孔 / 开口', [45, 55], [57, 61])
    await expect(input('宽')).toHaveValue('12')
    await expect(input('高')).toHaveValue('6')
    await expect(canvas.locator('[data-resize-handle]')).toHaveCount(8)
    await page.getByRole('combobox', { name: '形状用途', exact: true }).selectOption('through-slot')
    await expect(input('槽宽')).toBeDisabled()
    await expect(input('槽宽')).toHaveValue('2')
    await expect(input('槽长')).toHaveValue('12')
    await expect(canvas.locator('[data-resize-handle]')).toHaveCount(2)
    await expect(save).toBeEnabled()
    await canvas.evaluate(element => element.scrollIntoView({ block: 'center', behavior: 'instant' }))
    for (const handle of await canvas.locator('[data-handle-hit]').all()) {
      expect(await handle.evaluate(element => {
        const bounds = element.getBoundingClientRect()
        return element.parentElement?.contains(document.elementFromPoint(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2))
      }), 'The open inspector must not cover either slot resize handle').toBe(true)
    }
    const end = await screenPoint(canvas, 57, 58)
    const longer = await screenPoint(canvas, 63, 58)
    await page.mouse.move(end.x, end.y)
    await page.keyboard.down('Shift')
    await page.mouse.down()
    await page.mouse.move(longer.x, longer.y, { steps: 8 })
    await page.mouse.up()
    await page.keyboard.up('Shift')
    await expect(input('槽长')).toHaveValue('18')
    await expect(input('槽宽')).toHaveValue('2')
    await page.getByRole('combobox', { name: '插入方向', exact: true }).selectOption('back')
    await expect(canvas.getByTestId('joint-direction')).toHaveAttribute('aria-label', '从背面插入')
    await input('Y').fill('5'); await input('Y').press('Enter')
    await expect(save).toBeDisabled()
    await expect(page.getByTestId('part-3d-preview')).toHaveAttribute('data-wood-ready', 'true')
    await page.getByRole('combobox', { name: '形状用途', exact: true }).selectOption('cut')
    await expect(save).toBeEnabled()
    await expect(canvas.locator('[data-resize-handle]')).toHaveCount(8)
    await page.getByRole('button', { name: '撤销', exact: true }).click()
    await expect(save).toBeDisabled()
    await expect(input('槽宽')).toBeDisabled()
    await input('Y').fill('58'); await input('Y').press('Enter')
    await expect(save).toBeEnabled()

    await page.getByRole('button', { name: '清空', exact: true }).click()
    await page.getByRole('button', { name: '确认清空', exact: true }).click()
    await drawStarterRectangle(page)
    await tools.getByRole('button', { name: '孔 / 开口', exact: true }).click()
    await page.getByRole('button', { name: '边缘插槽', exact: true }).click()
    await dragMillimetres(page, canvas, [65, 40], [65, 58])
    await tools.getByRole('button', { name: '选择', exact: true }).click()
    await expect(canvas.locator('[data-shape-id]')).toHaveCount(2)
    await expect(input('槽宽')).toHaveValue('2')
    await expect(save).toBeEnabled()
    await expect(canvas.getByTestId('joint-direction')).toHaveAttribute('aria-label', '从上向下插入')
    await page.getByRole('combobox', { name: '插入方向', exact: true }).selectOption('end')
    await expect(save).toBeDisabled()
    await page.getByRole('combobox', { name: '插入方向', exact: true }).selectOption('start')
    await expect(save).toBeEnabled()
    await expect(canvas.locator('[data-resize-handle]')).toHaveCount(2)
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
    if (process.env.FWX_UI_CAPTURE_DIR) {
      await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
      await page.screenshot({ path: `${process.env.FWX_UI_CAPTURE_DIR}/joint-workspace-${viewport.width}.png`, fullPage: true })
    }
    expect(errors).toEqual([])
  })
}
