import { expect, test } from '@playwright/test'
import { drawStarterRectangle, dragMillimetres, screenPoint } from './part-studio-helpers'

for (const viewport of [{ width: 390, height: 844 }, { width: 768, height: 1024 }, { width: 1440, height: 900 }]) {
  test(`toolbar names and insertion guidance at ${viewport.width}px`, async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
    page.on('requestfailed', request => errors.push(`${request.method()} ${request.url()}: ${request.failure()?.errorText}`))
    await page.setViewportSize(viewport)
    await page.goto('/register')
    await page.getByRole('button', { name: '进入游客模式', exact: true }).click()
    await page.goto('/part-studio')
    const tools = page.getByTestId('sketch-toolbar')
    const headingY = await page.getByTestId('sketch-panel-heading').evaluate(element => element.getBoundingClientRect().y + window.scrollY)
    const stageHeight = await page.getByTestId('sketch-stage').evaluate(element => element.getBoundingClientRect().height)
    for (const button of await tools.getByRole('button').all()) {
      const label = await button.getAttribute('aria-label')
      // Disabled buttons must still explain their function when hovered.
      await button.hover()
      const tooltip = page.getByRole('tooltip')
      await expect(tooltip).toHaveText(label === '孔 / 开口' ? '矩形开孔' : label!)
      await expect(tooltip).toBeInViewport()
      const bounds = await tooltip.boundingBox()
      expect(bounds!.x).toBeGreaterThanOrEqual(0)
      expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(viewport.width)
      await page.mouse.move(1, 1)
      await expect(tooltip).toHaveCount(0)
    }
    const insert = tools.getByRole('button', { name: '插接口', exact: true })
    await insert.focus()
    await expect(page.getByRole('tooltip')).toHaveText('插接口')
    await page.keyboard.press('Escape')
    await expect(page.getByRole('tooltip')).toHaveCount(0)
    await insert.click()
    await expect(page.getByRole('tooltip')).toHaveCount(0)
    const hint = page.getByTestId('insertion-guidance')
    await expect(hint).toContainText('先画一块完整木板')
    await expect(hint).toBeInViewport()
    const canvas = await drawStarterRectangle(page)
    await insert.click()
    await expect(hint).toContainText('靠近红色板边')
    await expect(canvas.getByTestId('insertion-edge-guide')).toBeVisible()
    await canvas.evaluate(element => element.scrollIntoView({ block: 'center', behavior: 'instant' }))
    const inside = await screenPoint(canvas, 65, 65)
    await page.mouse.move(inside.x, inside.y)
    await expect(canvas).toHaveCSS('cursor', 'not-allowed')
    await page.mouse.click(inside.x, inside.y)
    await expect(hint).toContainText('请从木板外边缘向内拖动')
    await expect(page.getByRole('alert')).toHaveCount(1)
    await expect(canvas.locator('[data-shape-id]')).toHaveCount(1)
    const empty = await screenPoint(canvas, 10, 10)
    await page.mouse.click(empty.x, empty.y)
    await expect(hint).toContainText('请从木板外边缘向内拖动')
    const edge = await screenPoint(canvas, 65, 45)
    // The edge has a 12px acquisition range, not a one-pixel line.
    await page.mouse.move(edge.x, edge.y - 8)
    await expect(canvas).toHaveCSS('cursor', 'crosshair')
    await expect(hint).toContainText('已对准板边')
    await expect(page.getByRole('alert')).toHaveCount(0)
    const anchor = canvas.getByTestId('insertion-hover-anchor')
    await expect(anchor).toHaveAttribute('cx', '65')
    await expect(anchor).toHaveAttribute('cy', '45')
    await expect(hint).toBeInViewport()
    expect(await hint.evaluate(element => getComputedStyle(element).pointerEvents)).toBe('none')
    expect(await page.getByTestId('sketch-stage').evaluate(element => element.getBoundingClientRect().height)).toBe(stageHeight)
    expect(await page.getByTestId('sketch-panel-heading').evaluate(element => element.getBoundingClientRect().y + window.scrollY)).toBe(headingY)
    if (process.env.FWX_UI_CAPTURE_DIR) await page.screenshot({ path: `${process.env.FWX_UI_CAPTURE_DIR}/insertion-guidance-${viewport.width}.png` })
    await page.mouse.down()
    await expect(hint).toContainText('拖到槽底后松开')
    const bottom = await screenPoint(canvas, 65, 60)
    await page.mouse.move(bottom.x, bottom.y, { steps: 8 })
    await page.mouse.up()
    await expect(canvas.locator('[data-shape-id]')).toHaveCount(2)
    await expect(tools.getByRole('button', { name: '选择', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(hint).toHaveCount(0)
    await expect(anchor).toHaveCount(0)
    await expect(canvas.getByTestId('insertion-edge-guide')).toHaveCount(0)
    await expect(canvas.getByTestId('joint-bottom')).toHaveAttribute('cy', '60')
    await tools.getByRole('button', { name: '撤销', exact: true }).click()
    await insert.click()
    await dragMillimetres(page, canvas, [65, 45], [65, 30])
    await expect(hint).toContainText('向内拖动至少 2 mm')
    await expect(page.getByRole('alert')).toHaveCount(1)
    await expect(canvas.locator('[data-shape-id]')).toHaveCount(1)
    await tools.getByRole('button', { name: '选择', exact: true }).hover()
    await expect(page.getByRole('tooltip')).toHaveText('选择')
    if (process.env.FWX_UI_CAPTURE_DIR) await tools.screenshot({ path: `${process.env.FWX_UI_CAPTURE_DIR}/tool-guidance-strip-${viewport.width}.png` })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    expect(errors).toEqual([])
  })
}
