import { randomBytes } from 'node:crypto'
import { expect, test } from '@playwright/test'

// Local isolated API only (enforced by playwright.config.ts); no production writes.
for (const [width, height] of [[390, 844], [768, 1024], [1440, 900]]) {
  test(`privacy notices and refusal at ${width}px`, async ({ page, context }) => {
    await page.setViewportSize({ width, height })
    const errors: string[] = []
    const events: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    page.on('request', request => { if (request.url().endsWith('/analytics/events')) events.push(request.url()) })
    await page.goto('/')
    await page.waitForLoadState('networkidle')
    const notice = page.getByTestId('analytics-notice')
    await expect(notice).toBeVisible()
    await expect(notice.getByRole('button')).toHaveText(['不允许', '允许使用统计'])
    await expect(notice.getByRole('button', { name: '允许使用统计' })).toBeDisabled()
    await page.screenshot({ path: `/tmp/fwx-privacy-banner-${width}.png` })
    await notice.getByRole('link', { name: '隐私政策', exact: true }).click()
    await expect(page).toHaveURL(/\/privacy\/policy$/)
    await expect(page.getByRole('heading', { level: 1, name: '隐私政策', exact: true })).toBeVisible()
    await expect(notice).toHaveCount(0)
    for (const [slug, title] of [['policy', '隐私政策'], ['cookies', 'Cookie及类似技术说明'], ['data', '数据收集清单'], ['children', '儿童个人信息保护规则'], ['rights', '数据管理与权利说明']]) {
      await page.goto(`/privacy/${slug}`)
      await expect(page.getByRole('heading', { level: 1 })).toHaveText(title)
      await page.waitForLoadState('networkidle')
      if (slug === 'policy') await page.screenshot({ path: `/tmp/fwx-privacy-policy-${width}.png` })
      expect(await page.locator('article section').count()).toBeGreaterThanOrEqual(4)
      const lastAnchor = page.getByRole('navigation', { name: '本页目录' }).locator('ol a').last()
      await lastAnchor.click()
      await expect(page.locator('article section').last()).toBeInViewport()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    }
    await page.goto('/privacy')
    await expect(page.getByRole('heading', { name: '隐私与数据保护', exact: true })).toBeVisible()
    await page.waitForLoadState('networkidle')
    await page.screenshot({ path: `/tmp/fwx-privacy-index-${width}.png`, fullPage: true })
    await page.getByRole('link', { name: '管理隐私设置', exact: true }).click()
    await expect(page.getByText('当前选择：尚未选择')).toBeVisible()
    await page.getByRole('button', { name: '不允许', exact: true }).click()
    await expect(page.getByText('当前选择：不允许')).toBeVisible()
    await page.goto('/')
    await page.waitForLoadState('networkidle')
    await expect(notice).toHaveCount(0)
    await page.reload()
    await page.waitForLoadState('networkidle')
    await expect(notice).toHaveCount(0)
    const second = await context.newPage()
    await second.goto('/')
    await second.waitForLoadState('networkidle')
    await expect(second.getByTestId('analytics-notice')).toHaveCount(0)
    await second.close()
    await page.goto('/part-studio')
    await expect(page.getByText('二维设计', { exact: false }).first()).toBeVisible()
    await expect(notice).toHaveCount(0)
    expect(events).toHaveLength(0)
    expect(errors).toEqual([])
  })
}

test('real consent, cross-tab withdrawal, failed deletion and retry', async ({ page, context }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/privacy/settings')
  await page.getByLabel('我已满14周岁', { exact: true }).check()
  const granted = page.waitForResponse(response => response.url().endsWith('/analytics/consent') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '允许使用统计' }).click()
  expect((await granted).ok()).toBe(true)
  await expect(page.getByText('当前选择：允许使用统计')).toBeVisible()
  const second = await context.newPage()
  await second.goto('/privacy/settings')
  await expect(second.getByText('当前选择：允许使用统计')).toBeVisible()
  const received = page.waitForResponse(response => response.url().endsWith('/analytics/events') && response.request().method() === 'POST')
  expect((await received).ok()).toBe(true)
  await page.route('**/analytics/consent', route => route.request().method() === 'DELETE'
    ? route.fulfill({ status: 503, contentType: 'application/json', body: '{}' }) : route.continue())
  await page.getByRole('button', { name: '撤回并删除统计记录' }).click()
  await expect(page.getByText('已停止统计，历史记录删除未完成，请联网后重试。')).toBeVisible()
  await expect(second.getByText('当前选择：不允许')).toBeVisible()
  await expect(page.getByRole('button', { name: '允许使用统计' })).toBeDisabled()
  await page.unroute('**/analytics/consent')
  const deleted = page.waitForResponse(response => response.url().endsWith('/analytics/consent') && response.request().method() === 'DELETE')
  await page.getByRole('button', { name: '重试删除', exact: true }).click()
  expect((await deleted).ok()).toBe(true)
  await expect(page.getByText('已停止统计，本次授权的历史记录已删除。')).toBeVisible()
  await second.close()
  await page.goto('/')
  await page.waitForLoadState('networkidle')
  await expect(page.getByTestId('analytics-notice')).toHaveCount(0)
  await page.evaluate(() => localStorage.removeItem('fwx-analytics-consent-v1'))
  await page.reload()
  await expect(page.getByTestId('analytics-notice')).toBeVisible()
  expect(errors).toEqual([])
})

test('registration and logout require a new choice without inheriting visitor consent', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '不允许', exact: true }).click()
  await page.goto('/register')
  const suffix = randomBytes(6).toString('hex')
  await page.getByLabel('用户名', { exact: true }).fill(`e2e_${suffix}`)
  await page.getByLabel('邮箱', { exact: true }).fill(`e2e_${suffix}@example.test`)
  try {
    await page.getByLabel('密码', { exact: true }).fill(randomBytes(24).toString('hex'))
    await page.getByRole('button', { name: '创建账号', exact: true }).click()
    await expect(page).toHaveURL(/\/dashboard$/)
  } finally {
    if (await page.getByLabel('密码', { exact: true }).count()) await page.getByLabel('密码', { exact: true }).fill('')
  }
  await expect(page.getByTestId('analytics-notice')).toBeVisible()
  await page.getByRole('button', { name: '不允许', exact: true }).click()
  // Menu selector is based on the rendered account label, not a forged auth state.
  await page.locator('header button').filter({ hasText: `e2e_${suffix}` }).click()
  await expect(page.getByRole('link', { name: '隐私设置', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '退出登录', exact: true }).click()
  await expect(page.getByTestId('analytics-notice')).toBeVisible()
})

test('disabling collection still leaves withdrawal accessible', async ({ page }) => {
  await page.goto('/privacy/settings')
  await page.getByLabel('我已满14周岁', { exact: true }).check()
  await page.getByRole('button', { name: '允许使用统计' }).click()
  await expect(page.getByText('当前选择：允许使用统计')).toBeVisible()
  // Simulate the public off switch only; consent and deletion use the real test API.
  await page.route('**/analytics/config', route => route.fulfill({ json: { enabled: false, noticeVersion: 1, retentionDays: 90, environment: 'test' } }))
  await page.reload()
  await expect(page.getByText('当前未启用使用统计，不会新增采集。')).toBeVisible()
  const deleted = page.waitForResponse(response => response.url().endsWith('/analytics/consent') && response.request().method() === 'DELETE')
  await page.getByRole('button', { name: '撤回并删除统计记录' }).click()
  expect((await deleted).ok()).toBe(true)
  await expect(page.getByText('本次授权的历史统计记录已删除。')).toBeVisible()
})
