const test = require('node:test')
const assert = require('node:assert/strict')
const { once } = require('node:events')
const { randomBytes, randomUUID } = require('node:crypto')
const mongoose = require('mongoose')
const { createApp } = require('../src/app')
const { createConfig } = require('../src/config/env')

test('analytics is disabled by default and enabled collection requires an independent secret', async () => {
  assert.equal(createConfig({ NODE_ENV: 'test' }).analytics?.enabled, false)
  assert.throws(() => createConfig({ NODE_ENV: 'test', ANALYTICS_ENABLED: 'true' }), /ANALYTICS_SECRET/)
})

const mongoUri = process.env.FWX_TEST_MONGO_URI
test('first-party analytics enforces consent, authority, deduplication and deletion', { skip: !mongoUri }, async (t) => {
  assert.match(mongoUri, /^mongodb:\/\/(127\.0\.0\.1|localhost):\d+(\/[^?]*)?$/)
  const dbName = `fwx_analytics_${randomBytes(8).toString('hex')}`
  await mongoose.connect(mongoUri, { dbName })
  const key = randomBytes(24).toString('hex')
  const app = createApp(createConfig({ NODE_ENV: 'test', JWT_SECRET: randomBytes(48).toString('hex'), ADMIN_ACCESS_KEY: key, ANALYTICS_ENABLED: 'true', ANALYTICS_SECRET: randomBytes(48).toString('hex'), RATE_LIMIT_DISABLED: 'true' }))
  const server = app.listen(0, '127.0.0.1')
  await once(server, 'listening')
  const base = `http://127.0.0.1:${server.address().port}/api`
  const send = async (url, method = 'GET', body, token, receipt, adminKey) => {
    const response = await fetch(base + url, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(receipt ? { 'X-FWX-Analytics-Consent': receipt } : {}), ...(adminKey ? { 'X-Admin-Access-Key': adminKey } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) })
    return { status: response.status, body: await response.json() }
  }
  const event = () => ({ eventId: randomUUID(), sessionId: randomUUID(), occurredAt: new Date().toISOString(), eventName: 'page_viewed', route: 'home', release: 'test', properties: { source: 'direct', device: 'desktop' } })
  try {
    await t.test('public configuration states collection and no-consent events are rejected', async () => {
      const config = await send('/analytics/config')
      assert.equal(config.status, 200)
      assert.equal(config.body.enabled, true)
      assert.equal(config.body.retentionDays, 90)
      assert.equal((await send('/analytics/events', 'POST', { events: [event()] })).status, 401)
    })
    const body = { anonymousId: randomUUID(), noticeVersion: 1, ageConfirmation: 'age_14_or_over' }
    assert.equal((await send('/analytics/consent', 'POST', { ...body, ageConfirmation: 'under_14' })).status, 400)
    const grant = await send('/analytics/consent', 'POST', body)
    assert.equal(grant.status, 201)
    const receipt = grant.body.receipt
    const sample = event()
    await t.test('valid retry records one event; input cannot add PII or server events', async () => {
      const Event = require('../src/models/AnalyticsEvent')
      const indexes = await Event.collection.indexes()
      assert.ok(indexes.some(index => index.key.consentId === 1 && index.key.eventId === 1 && index.unique === true))
      const initial = await Promise.all(Array.from({ length: 4 }, () => send('/analytics/events', 'POST', { events: [sample] }, undefined, receipt)))
      assert.ok(initial.every(result => result.status === 202))
      assert.equal(await Event.countDocuments({ eventId: sample.eventId }), 1)
      assert.equal((await send('/analytics/events', 'POST', { events: [{ ...sample, properties: { source: 'school' } }] }, undefined, receipt)).status, 409)
      assert.equal((await send('/analytics/events', 'POST', { events: [{ ...event(), userId: 'forged' }] }, undefined, receipt)).status, 400)
      assert.equal((await send('/analytics/events', 'POST', { events: [{ ...event(), properties: { email: 'private@example.test' } }] }, undefined, receipt)).status, 400)
      assert.equal((await send('/analytics/events', 'POST', { events: [{ ...event(), eventName: 'auth_completed', properties: { method: 'register' } }] }, undefined, receipt)).status, 400)
      assert.equal((await send('/analytics/events', 'POST', { events: Array.from({ length: 21 }, event) }, undefined, receipt)).status, 400)
      assert.equal((await send('/analytics/events', 'POST', { events: [{ ...event(), occurredAt: '2000-01-01T00:00:00.000Z' }] }, undefined, receipt)).status, 400)
      const stored = await Event.findOne({ eventId: sample.eventId }).lean()
      assert.equal(stored.environment, 'test')
      assert.doesNotMatch(JSON.stringify(stored), /private@example|anonymousId|userId|ipAddress|userAgent/)
      assert.ok(stored.expiresAt > stored.receivedAt)
    })
    const register = async (name) => (await send('/auth/register', 'POST', { username: name, email: `${name}@example.test`, password: randomBytes(16).toString('hex') })).body
    const user = await register('analytics-user')
    const other = await register('analytics-other')
    const accountGrant = await send('/analytics/consent', 'POST', { ...body, anonymousId: randomUUID() }, user.token)
    await t.test('concurrent event retries use the real unique index and consent expiry blocks ingestion', async () => {
      const Event = require('../src/models/AnalyticsEvent')
      const concurrent = event()
      const retries = await Promise.all(Array.from({ length: 4 }, () => send('/analytics/events', 'POST', { events: [concurrent] }, undefined, receipt)))
      assert.ok(retries.every(result => result.status === 202))
      assert.equal(await Event.countDocuments({ eventId: concurrent.eventId }), 1)
      const Consent = require('../src/models/AnalyticsConsent')
      const jwt = require('jsonwebtoken')
      const expired = await send('/analytics/consent', 'POST', { ...body, anonymousId: randomUUID() })
      const cid = jwt.decode(expired.body.receipt).cid
      await Consent.updateOne({ _id: cid }, { $set: { expiresAt: new Date(Date.now() - 1000) } })
      assert.equal((await send('/analytics/events', 'POST', { events: [event()] }, undefined, expired.body.receipt)).status, 401)
      const expiredToken = jwt.sign({ cid }, app.locals.config.analytics.secret, { audience: 'fwx-analytics', issuer: 'fwx', expiresIn: -1 })
      assert.equal((await send('/analytics/consent', 'DELETE', undefined, undefined, expiredToken)).status, 200)
      const huge = await send('/analytics/events', 'POST', { events: [], extra: 'x'.repeat(30000) }, undefined, receipt)
      assert.equal(huge.status, 413)
    })
    await t.test('a receipt is bound to its account and guest receipts cannot become logged-in identity', async () => {
      assert.equal((await send('/analytics/events', 'POST', { events: [event()] }, other.token, accountGrant.body.receipt)).status, 401)
      assert.equal((await send('/analytics/events', 'POST', { events: [event()] }, user.token, receipt)).status, 401)
      assert.equal((await send('/analytics/consent', 'DELETE', undefined, other.token, accountGrant.body.receipt)).status, 401)
      assert.equal((await send('/analytics/events', 'POST', { events: [event()] }, user.token, accountGrant.body.receipt)).status, 202)
    })
    await t.test('authoritative design events exclude empty drafts, unchanged autosaves and metadata-only updates', async () => {
      const payload = { localId: 'tracked-design', name: 'Private name never tracked', designData: { id: 'tracked-design', name: 'Private name never tracked', updatedAt: new Date().toISOString(), buildMode: 'guided', currentStep: 'HUB', stepReached: 0, parts: [] } }
      const first = await send('/drone-designs', 'PUT', payload, user.token, accountGrant.body.receipt)
      assert.equal(first.status, 200)
      await app.locals.analytics.drain()
      const Event = require('../src/models/AnalyticsEvent')
      assert.equal(await Event.countDocuments({ eventName: 'design_saved', 'properties.nonempty': false }), 1)
      const Design = require('../src/models/DroneDesign')
      const saved = await Design.findOne({ ownerId: user.user.id, localId: payload.localId }).lean()
      const savedEvent = await Event.findOne({ eventName: 'design_saved', 'properties.designId': String(saved._id) }).lean()
      assert.equal(savedEvent.properties.localDesignId, saved.localId)
      assert.equal(savedEvent.properties.designId, String(saved._id))
      assert.equal(savedEvent.properties.designId, first.body.design.id)
      payload.designData.parts = [{ instanceId: 'hub-1', partId: 'FW-HUB-001', category: 'mainboard', position: [0, 0, 0], rotation: [0, 0, 0] }]
      assert.equal((await send('/drone-designs', 'PUT', payload, user.token, accountGrant.body.receipt)).status, 200)
      payload.designData.updatedAt = new Date().toISOString()
      payload.name = 'Renamed private work'
      assert.equal((await send('/drone-designs', 'PUT', payload, user.token, accountGrant.body.receipt)).status, 200)
      await app.locals.analytics.drain()
      assert.equal(await Event.countDocuments({ eventName: 'design_saved', 'properties.nonempty': true }), 1)
      assert.doesNotMatch(JSON.stringify(await Event.find({ eventName: 'design_saved' }).lean()), /Private name|Renamed|position|FW-HUB/)
      // An invalid/revoked analytics header must not break an otherwise valid business write.
      assert.equal((await send('/drone-designs', 'PUT', payload, user.token, 'invalid-receipt')).status, 200)
      await app.locals.analytics.drain()
    })
    await t.test('first observation of an old unchanged work is not presented as a new edit', async () => {
      const Design = require('../src/models/DroneDesign')
      const old = await Design.create({ ownerId: user.user.id, name: 'Old existing work', localId: 'old-existing', parts: [{ instanceId: 'old-hub', partId: 'FW-HUB-001', category: 'mainboard', position: [0, 0, 0], rotation: [0, 0, 0] }] })
      assert.equal((await send(`/drone-designs/${old._id}`, 'PATCH', { name: 'Metadata only' }, user.token, accountGrant.body.receipt)).status, 200)
      await app.locals.analytics.drain()
      const Event = require('../src/models/AnalyticsEvent')
      const observed = await Event.findOne({ eventName: 'design_saved', 'properties.designId': String(old._id) }).lean()
      assert.equal(observed.properties.change, 'observed')
    })
    await t.test('aggregate reports require account, admin role and admin key', async () => {
      assert.equal((await send('/analytics/summary')).status, 401)
      assert.equal((await send('/analytics/summary', 'GET', undefined, user.token, undefined, key)).status, 403)
      const User = require('../src/models/User')
      await User.updateOne({ _id: other.user.id }, { $set: { role: 'admin' } })
      assert.equal((await send('/analytics/summary', 'GET', undefined, other.token)).status, 401)
      const summary = await send('/analytics/summary', 'GET', undefined, other.token, undefined, key)
      assert.equal(summary.status, 200)
      assert.equal(summary.body.registeredActiveCreators, 1)
      assert.equal(summary.body.uniqueSavedDesigns, 2)
      assert.doesNotMatch(JSON.stringify(summary.body), /actorId|receipt|email|analytics-user/)
      const csv = await fetch(base + '/analytics/export.csv', { headers: { Authorization: `Bearer ${other.token}`, 'X-Admin-Access-Key': key } })
      assert.equal(csv.status, 200)
      assert.match(csv.headers.get('content-type'), /text\/csv/)
      assert.match(await csv.text(), /registered_active_creators,1/)
      assert.equal((await send('/analytics/summary?from=2020-01-01T00%3A00%3A00Z', 'GET', undefined, other.token, undefined, key)).status, 400)
    })
    await t.test('free-form legacy local IDs are omitted from successful design events', async () => {
      const payload = { localId: 'private@example.test', name: 'Legacy private work', designData: { id: 'legacy-work', name: 'Legacy private work', updatedAt: new Date().toISOString(), buildMode: 'guided', currentStep: 'HUB', stepReached: 0, parts: [] } }
      const saved = await send('/drone-designs', 'PUT', payload, user.token, accountGrant.body.receipt)
      assert.equal(saved.status, 200)
      await app.locals.analytics.drain()
      const Event = require('../src/models/AnalyticsEvent')
      const recorded = await Event.findOne({ eventName: 'design_saved', 'properties.designId': saved.body.design.id }).lean()
      assert.equal(Object.hasOwn(recorded.properties, 'localDesignId'), false)
      assert.doesNotMatch(JSON.stringify(recorded), /private@example|Legacy private/)
    })
    await t.test('part/program/publication/remix successes are authoritative and repeated writes do not inflate them', async () => {
      const part = { name: 'Private part name', category: 'guard', geometry: { contour: 'M0 0 H20 V20 H0 Z', holes: [], thicknessMm: 2, bboxMm: { w: 20, h: 20 } }, sockets: [], manufacturability: { closed: true, minFeatureMm: 2, withinBoard: true, passed: false }, flightImpact: { massG: 1 }, assets: {} }
      const createdPart = await send('/custom-parts', 'POST', part, user.token, accountGrant.body.receipt)
      assert.equal(createdPart.status, 201)
      assert.equal((await send(`/custom-parts/${createdPart.body.data.id}`, 'PUT', part, user.token, accountGrant.body.receipt)).status, 200)
      for (const category of ['joint', 'deco']) assert.equal((await send('/custom-parts', 'POST', { ...part, category }, user.token, accountGrant.body.receipt)).status, 201)
      part.geometry.contour = 'M0 0 H20 V20 H1 Z'
      assert.equal((await send(`/custom-parts/${createdPart.body.data.id}`, 'PUT', part, user.token, accountGrant.body.receipt)).status, 200)
      const program = { name: 'Private program name', blocklyXml: '<xml><block type="takeoff"/></xml>', commandProgram: { version: '1.0', metadata: { name: 'Private program name', author: 'Private author', createdAt: new Date().toISOString() }, commands: [{ type: 'takeoff', params: { altitudeCm: 100 } }] } }
      const createdProgram = await send('/programs', 'POST', program, user.token, accountGrant.body.receipt)
      assert.equal(createdProgram.status, 201)
      assert.equal((await send(`/programs/${createdProgram.body.program.id}`, 'PATCH', program, user.token, accountGrant.body.receipt)).status, 200)
      const Design = require('../src/models/DroneDesign')
      const design = await Design.findOne({ localId: 'tracked-design' }).lean()
      assert.equal((await send(`/drone-designs/${design._id}`, 'PATCH', { visibility: 'public', reusable: true, programId: createdProgram.body.program.id }, user.token, accountGrant.body.receipt)).status, 200)
      const published = await send('/community/posts', 'POST', { designId: String(design._id) }, user.token, accountGrant.body.receipt)
      assert.equal(published.status, 201)
      assert.equal((await send('/community/posts', 'POST', { designId: String(design._id) }, user.token, accountGrant.body.receipt)).status, 200)
      const remixer = await register('analytics-remixer')
      const remixConsent = await send('/analytics/consent', 'POST', { ...body, anonymousId: randomUUID() }, remixer.token)
      assert.equal((await send(`/community/posts/${published.body.post.id}/fork`, 'POST', {}, remixer.token, remixConsent.body.receipt)).status, 201)
      assert.equal((await send(`/community/posts/${published.body.post.id}/fork`, 'POST', {}, remixer.token, remixConsent.body.receipt)).status, 200)
      await app.locals.analytics.drain()
      const Event = require('../src/models/AnalyticsEvent')
      assert.equal(await Event.countDocuments({ eventName: 'custom_part_saved' }), 4)
      assert.equal(await Event.countDocuments({ eventName: 'custom_part_saved', 'properties.category': 'connector' }), 1)
      assert.equal(await Event.countDocuments({ eventName: 'custom_part_saved', 'properties.category': 'decoration' }), 1)
      assert.equal(await Event.countDocuments({ eventName: 'program_saved' }), 1)
      assert.equal(await Event.countDocuments({ eventName: 'community_published' }), 1)
      assert.equal(await Event.countDocuments({ eventName: 'design_remixed' }), 1)
      assert.doesNotMatch(JSON.stringify(await Event.find().lean()), /Private part name|Private program name|Private author|contour|blocklyXml/)
    })
    await t.test('analytics storage failure cannot fail a business save and retry remains collectable', async (t) => {
      const Event = require('../src/models/AnalyticsEvent')
      const payload = { localId: 'store-retry', name: 'Storage retry', designData: { id: 'store-retry', name: 'Storage retry', updatedAt: new Date().toISOString(), buildMode: 'guided', currentStep: 'HUB', stepReached: 0, parts: [] } }
      const broken = t.mock.method(Event, 'bulkWrite', async () => { throw new Error('database temporarily unavailable') })
      assert.equal((await send('/drone-designs', 'PUT', payload, user.token, accountGrant.body.receipt)).status, 200)
      await app.locals.analytics.drain()
      broken.mock.restore()
      const retried = await send('/drone-designs', 'PUT', payload, user.token, accountGrant.body.receipt)
      assert.equal(retried.status, 200)
      await app.locals.analytics.drain()
      assert.equal(await Event.countDocuments({ eventName: 'design_saved', 'properties.designId': retried.body.design.id }), 1)
    })
    await t.test('successful authentication is collected only with a valid current guest consent', async () => {
      const password = randomBytes(16).toString('hex')
      const registered = await send('/auth/register', 'POST', { username: 'analytics-auth', email: 'analytics-auth@example.test', password }, undefined, receipt)
      assert.equal(registered.status, 201)
      assert.equal((await send('/auth/login', 'POST', { email: 'analytics-auth@example.test', password }, undefined, receipt)).status, 200)
      assert.equal((await send('/auth/login', 'POST', { email: 'analytics-auth@example.test', password: 'wrong-password' }, undefined, receipt)).status, 401)
      await app.locals.analytics.drain()
      const Event = require('../src/models/AnalyticsEvent')
      assert.equal(await Event.countDocuments({ eventName: 'auth_completed' }), 2)
    })
    await t.test('withdrawal racing an in-flight batch leaves no retained events', async () => {
      const racing = await send('/analytics/consent', 'POST', { ...body, anonymousId: randomUUID() })
      const events = Array.from({ length: 20 }, event)
      const results = await Promise.all([send('/analytics/events', 'POST', { events }, undefined, racing.body.receipt), send('/analytics/consent', 'DELETE', undefined, undefined, racing.body.receipt)])
      assert.ok([202, 401].includes(results[0].status))
      assert.equal(results[1].status, 200)
      const Event = require('../src/models/AnalyticsEvent')
      assert.equal(await Event.countDocuments({ eventId: { $in: events.map(item => item.eventId) } }), 0)
    })
    await t.test('partial database writes after withdrawal are cleaned even when bulkWrite throws', async (t) => {
      const racing = await send('/analytics/consent', 'POST', { ...body, anonymousId: randomUUID() })
      const Event = require('../src/models/AnalyticsEvent')
      const originalWrite = Event.bulkWrite
      const sample = event()
      const broken = t.mock.method(Event, 'bulkWrite', async (operations, options) => {
        assert.equal((await send('/analytics/consent', 'DELETE', undefined, undefined, racing.body.receipt)).status, 200)
        await originalWrite.call(Event, operations, options)
        throw new Error('simulated partial database failure')
      })
      const result = await send('/analytics/events', 'POST', { events: [sample] }, undefined, racing.body.receipt)
      broken.mock.restore()
      assert.ok([401, 503].includes(result.status))
      assert.equal(await Event.countDocuments({ eventId: sample.eventId }), 0)
    })
    await t.test('reports exclude withdrawn receipts even if deletion is still pending', async () => {
      const before = await send('/analytics/summary', 'GET', undefined, other.token, undefined, key)
      const grant = await send('/analytics/consent', 'POST', { ...body, anonymousId: randomUUID() })
      assert.equal((await send('/analytics/events', 'POST', { events: [event()] }, undefined, grant.body.receipt)).status, 202)
      const Consent = require('../src/models/AnalyticsConsent')
      const jwt = require('jsonwebtoken')
      await Consent.updateOne({ _id: jwt.decode(grant.body.receipt).cid }, { $set: { revokedAt: new Date() } })
      const after = await send('/analytics/summary', 'GET', undefined, other.token, undefined, key)
      assert.equal(after.body.totalEvents, before.body.totalEvents)
    })
    await t.test('withdrawal deletes collected events and prevents replay', async () => {
      assert.equal((await send('/analytics/consent', 'DELETE', undefined, undefined, receipt)).status, 200)
      assert.equal((await send('/analytics/consent', 'DELETE', undefined, undefined, receipt)).status, 200)
      assert.equal((await send('/analytics/events', 'POST', { events: [event()] }, undefined, receipt)).status, 401)
      const Event = require('../src/models/AnalyticsEvent')
      assert.equal(await Event.countDocuments({ eventId: sample.eventId }), 0)
    })
    await t.test('account withdrawal works after logout and deletes only that receipt scope', async () => {
      assert.equal((await send('/analytics/consent', 'DELETE', undefined, undefined, accountGrant.body.receipt)).status, 200)
      const Event = require('../src/models/AnalyticsEvent')
      assert.equal(await Event.countDocuments({ eventName: 'design_saved' }), 0)
    })
    await t.test('disabled collection stays off and its separate rate budget does not consume business requests', async () => {
      const disabledApp = createApp(createConfig({ NODE_ENV: 'test', JWT_SECRET: randomBytes(48).toString('hex') }))
      const disabledServer = disabledApp.listen(0, '127.0.0.1')
      await once(disabledServer, 'listening')
      const origin = `http://127.0.0.1:${disabledServer.address().port}`
      try {
        const configs = await Promise.all(Array.from({ length: 105 }, () => fetch(origin + '/api/analytics/config')))
        assert.ok(configs.every(response => response.status === 200))
        assert.equal((await configs[0].json()).enabled, false)
        assert.equal((await fetch(origin + '/api/health')).status, 200)
        const blocked = await fetch(origin + '/api/analytics/events', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ events: [event()] }) })
        assert.equal(blocked.status, 503)
      } finally {
        disabledServer.close()
        await once(disabledServer, 'close')
      }
    })
  } finally {
    server.close()
    await once(server, 'close')
    assert.equal(mongoose.connection.name, dbName)
    await mongoose.connection.dropDatabase()
    await mongoose.disconnect()
  }
})
